- hosts: localhost
  vars_files:
    smtp_secrets.yml

  tasks:
  - name: Sending an e-mail using Gmail SMTP servers
    mail:
      host: smtp.gmail.com
      port: 587
      username: jmanuelcalvo@gmail.com
      password: "{{ email_smtp_password }}"
      to: jmanuelcalvo@gmail.com
      subject: Se solicita la programación en la próxima ventana de la configuración anexa
      body: System {{ ansible_hostname }} has been successfully provisioned.
