---
- name: Traer informacion del VmWare
  hosts:  localhost
  become: false
  collections:
    - community.vmware
  vars:
    - vcenter_hostname: portal.vc.opentlc.com
    - vcenter_username: 
    - vcenter_password: 


  tasks:
  - name: Gather all registered virtual machines
    community.vmware.vmware_vm_info:
      hostname: '{{ vcenter_hostname }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
    delegate_to: localhost
    register: vminfo

  - debug:
      var: vminfo.virtual_machines
