---
- name: Traer informacion del VmWare
  hosts:  localhost
  become: false
  vars:
    - vcenter_hostname: portal.vc.opentlc.com
    - vcenter_username: sandbox-9l52q@vc.opentlc.com
    - vcenter_password: sA,id-DxzBC2


  tasks:
  - name: Gather all registered virtual machines
    community.vmware.vmware_vm_info:
      hostname: '{{ vcenter_hostname }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
    delegate_to: localhost
    register: vminfo

  - debug:
      var: vminfo.virtual_machines
