- hosts: localhost
  connection: local
  gather_facts: false
  vars:
    vmware:
      host: '{{ lookup("env", "VMWARE_HOST") }}'
      username: '{{ lookup("env", "VMWARE_USER") }}'
      password: '{{ lookup("env", "VMWARE_PASSWORD") }}'
  collections:
    - community.vmware
  tasks:
  - name: Set the state of a virtual machine to poweroff on off
    community.vmware.vmware_guest_powerstate:
      hostname: "{{ host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      folder: /SDDC-Datacenter/Workloads/sandbox-9l52q
      name: "{{ vm_guest_name }}"
      state: "{{ vm_state }}"
    delegate_to: localhost
    register: deploy  
  
  - name: Print the generated password
    debug:
      msg: "The Output is {{ deploy }}"
